port: 3000

secrets:
    cookie: shhhhhhhhh...

db:
  mongo:
    url: mongodb://localhost:27017/CrossOver
    
  redis:
    url: redis://localhost:6379
    secret: shhhhhhhh22222...
    no_ready_check: true